RepoPractice/Controllers/BuyerController.cs
using RepoPractice.Models.DAL.Product;
using RepoPractice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Net.Mail;
using System.Net;
using System.Web.UI.WebControls;

namespace RepoPractice.Controllers
{
    #region
    /// <summary>
    /// Contains all buyer actions
    /// </summary>
    public class BuyerController : Controller
    {
        ShoppingCartDBContext db = new ShoppingCartDBContext();
        private IRepository<UserModel> userObj;
        private IRepository<ProductModel> productObj;
        private IRepository<CartModel> cartObj;
        private IRepository<OrderModel> orderObj;
        private IRepository<WalletModel> walletObj;


        public BuyerController()
        {
            this.productObj = new GenericRepository<ProductModel>();
            this.userObj = new GenericRepository<UserModel>();
            this.cartObj = new GenericRepository<CartModel>();
            this.orderObj = new GenericRepository<OrderModel>();
            this.walletObj = new GenericRepository<WalletModel>();
        }

        [Authorize]
        public ActionResult Index()
        {
            try
            {
                return View(from i in productObj.GetAll().OrderByDescending(x => x.ProductId) select i);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #region
        /// <summary>
        /// Send order confirmation mail to buyer
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult SendMail()
        {
            try
            {

                MailMessage mm = new MailMessage("radhakrishna36495@gmail.com", User.Identity.Name);
                mm.Subject = "Order Confirmed";
                mm.Body = "Your Order Id " + (int)Session["lastOrderId"] + " Order is Confirmed";
                mm.IsBodyHtml = false;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;


                NetworkCredential nc = new NetworkCredential("radhakrishna36495@gmail.com", "iufedzbfhqlpypdl");
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = nc;
                smtp.Send(mm);

                return RedirectToAction("BuyerDisplayAllProduct");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #endregion

        #region
        /// <summary>
        /// Display all products on home page
        /// </summary>
        /// <returns></returns>
        public ActionResult BuyerDisplayAllProduct()
        {
            try
            {
                return View(from i in productObj.GetAll() select i);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #endregion

        #region
        /// <summary>
        /// Add to cart action
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult AddToCart(int id)
        {

            ProductModel p = productObj.GetAllById(Convert.ToInt32(id));
            return View(p);

        }
        List<CartModel> li = new List<CartModel>();
        [HttpPost]
        public ActionResult AddToCart(/*ProductModel pi*/ string qty, int? Id)
        {

            ProductModel po = productObj.GetAllById(Convert.ToInt32(Id));
            CartModel co = new CartModel();
            co.ProductModel_ProductId = po.ProductId;
            co.productname = po.ProductName;
            co.price = (int)po.Price;
            co.Quantity = Convert.ToInt32(qty);
            co.TotalAmount = co.price * co.Quantity;

            if (TempData["cart"] == null)
            {
                li.Add(co);
                TempData["cart"] = li;
            }
            else
            {
                List<CartModel> li2 = TempData["cart"] as List<CartModel>;
                int flag = 0;
                foreach (var item in li2)
                {
                    if (item.CartId == co.ProductModel_ProductId)
                    {
                        item.Quantity = co.Quantity;
                        item.TotalAmount = co.TotalAmount;
                        flag = 1;
                    }
                }
                if (flag == 0)
                {
                    li2.Add(co);
                }

                TempData["cart"] = li2;
            }
            TempData.Keep();

            cartObj.Add(co);
            cartObj.Save();



            return RedirectToAction("ViewCart");

        }
        #endregion

        #region
        /// <summary>
        /// Remove from cart
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Remove(int? id)
        {
            try
            {
                cartObj.Delete(Convert.ToInt32(id));
                cartObj.Save();
                return RedirectToAction("ViewCart");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #endregion

        #region
        /// <summary>
        /// Display Cart
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult ViewCart()
        {
            try
            {
                List<CartModel> cart = cartObj.GetAll().ToList();
                var cartId = (from x in cart select x.CartId).FirstOrDefault();
                if (cartId != 0)
                {

                    var GrandTotal = Convert.ToInt32((from x in cart select x.TotalAmount).Sum());

                    Session["GrandTotal"] = GrandTotal;

                    ViewBag.GrandTotal = (int)Session["GrandTotal"];
                    return View(from i in cartObj.GetAll() select i);

                }
                else
                {
                    return RedirectToAction("CartNull");
                }

            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        public ActionResult CartNull()
        {
            return View();
        }
        #endregion

        #region
        /// <summary>
        /// to update user profile
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult UpdateProfile()
        {
            var id = (int)Session["UserId"];

            UserModel u = userObj.GetAllById(id);
            return View(u);
        }

        [HttpPost]
        public ActionResult UpdateProfile(UserModel collection)
        {
            try
            {
                userObj.Update(collection);
                userObj.Save();
                return RedirectToAction("Checkout");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #endregion

        public ActionResult CreateWallet()
        {
            var id = (int)Session["UserId"];

            List<WalletModel> wmList = walletObj.GetAll().ToList();

            var credentials = db.WalletSet.Where(x => x.UserModel_UserId == id).FirstOrDefault();
            if (credentials != null)
            {
                var widList = (from i in wmList where i.UserModel_UserId == id select i.UserModel_UserId).ToList();
                var wid = Convert.ToInt32(widList[0]);

                if (wid == id)
                {
                    return RedirectToAction("AddBalance");
                }
                return Content("Unhandled Exception");
            }
            else
            {
                WalletModel wm = new WalletModel();

                wm.CurrentBalance = 0;
                wm.UserModel_UserId = id;
                walletObj.Add(wm);
                walletObj.Save();

                return RedirectToAction("AddBalance");
            }
        }

        #region
        /// <summary>
        /// To add balance in wallet
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult AddBalance()
        {
            try
            {
                var id = (int)Session["UserId"];

                var credentials = db.WalletSet.Where(x => x.UserModel_UserId == id).FirstOrDefault();
                var wid = credentials.WalletId;

                WalletModel w = walletObj.GetAllById(wid);
                return View(w);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBalance(WalletModel collection)
        {
            try
            {
                walletObj.Update(collection);
                walletObj.Save();
                return RedirectToAction("Checkout");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #endregion

        #region
        /// <summary>
        /// direct to checkout page
        /// </summary>
        /// <returns></returns>
        public ActionResult Checkout()
        {
            try
            {
                TempData.Keep();
                return View();
            }
            catch (Exception ex)
            {

RepoPractice/Views/Buyer/AddBalance.cshtml
@model RepoPractice.Models.WalletModel

@{
    ViewBag.Title = "AddBalance";
}

<h2>AddBalance</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WalletModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WalletId)

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.UserModel_UserId, "UserModel_UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserModel_UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserModel_UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RepoPractice/Views/Buyer/AddToCart.cshtml
@model RepoPractice.Models.ProductModel
@{
    ViewBag.Title = "Addtocart";
}
<br />
<br />
<br />
<div style="background-color:lightcoral;">
    @using (@Html.BeginForm())
    {<div class="container" style="margin-top:70px">
            <a href="javascript:void(0);" onclick="history.go(-1);"><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
    <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
</svg></a>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <img style="min-height:200px; width:200px;" src="@Url.Content(Model.Image)" />
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <h1>Product Name: @Model.ProductName</h1>
                    <h2>Price: @Model.Price PKR</h2>
                    <input type="number" name="qty" value="0" id="qty1" min="1" max="10" />
                    <input type="submit" value="Submit" class="btn btn-danger" />
                </div>
            </div>
        </div>

    }
</div>

RepoPractice/Views/Buyer/BuyerDisplayAllProduct.cshtml
@model IEnumerable<RepoPractice.Models.ProductModel>

<div id="carouselExampleIndicators" class="carousel slide mt-5 rounded-4 shadow" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner rounded-4">
        <div class="carousel-item active">
            <img src="~/Content/Image/carousel1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Content/Image/carousel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Content/Image/carousel3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="mt-lg-5">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="card shadow col-lg-3 m-4" style="width: 18rem;">
                <img src="@Url.Content(item.Image)" class="card-img-top" alt="...">
                <div class="card-body">
                    <lable>Product Name : </lable><h5 class="card-title">@Html.DisplayFor(modelItem => item.ProductName)</h5>
                    <lable>Price : </lable><p class="card-text">@Html.DisplayFor(modelItem => item.Price)</p>
                    <button class="btn btn-primary">@Html.ActionLink("Add To Cart", "AddToCart", new { id = item.ProductId }, new { @style = "text-decoration : none;color : white" })</button>
                </div>
            </div>
            <br />
        }
    </div>
</div>

@*@Html.ActionLink("Edit", "UpdateProducts", new { id = item.ProductId }) |
    @Html.ActionLink("Details", "DisplayAllProducts", new { id = item.ProductId }) |
    @Html.ActionLink("Delete", "DeleteProduct", new { id = item.ProductId })
            </td>*@

RepoPractice/Views/Buyer/CartNull.cshtml

@{
    ViewBag.Title = "CartNull";
}
<div style="margin-top:100px">
    <h2>Cart is Null</h2>
    <button class="btn btn-outline-success">@Html.ActionLink("Add Something To Cart", "BuyerDisplayAllProduct", "Buyer")</button>
</div>

RepoPractice/Views/Buyer/Checkout.cshtml
@model RepoPractice.Models.CartModel

@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>
<div class="container" style="margin-top:70px">
    <a href="javascript:void(0);" onclick="history.go(-1);">
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
        </svg>
    </a>
    </div>
    <div class="mt-5">
        <button class="btn btn-outline-success">@Html.ActionLink("Update Profile", "UpdateProfile", "Buyer")</button>
        <button class="btn btn-outline-success">@Html.ActionLink("Add Balance", "CreateWallet", "Buyer")</button>
        <button class="btn btn-outline-success">@Html.ActionLink("Buy Now", "PaymentMode", "Buyer")</button>
    </div>

RepoPractice/Views/Buyer/FinalPage.cshtml
<div>
    <div class="row" style="margin-top: 100px">
        <div class="card shadow col-lg-3" style="width: 18rem;">
            <div class="card-body">
                <lable>Order ID : </lable><p class="card-title">@Session["lastOrderId"]</p>
                <lable>Order Date : </lable><p class="card-text">@Session["lastOrderDate"]</p>
                <lable>Mode Of Payment : </lable><p class="card-title">@Session["lastOrderPaymentMode"]</p>
                <lable>Amount Paid : </lable><p class="card-text">@Session["lastOrderAmountPaid"]</p>
            <button class="btn btn-outline-success">@Html.ActionLink("Send On Mail", "SendMail", "Buyer")</button>
        </div>
    </div>
    <br />
</div>
</div>


RepoPractice/Views/Buyer/FinalPages.cshtml
@model IEnumerable<RepoPractice.Models.OrderModel>

<div>
    <div class="row" style="margin-top: 100px">
            <div class="card shadow col-lg-3" style="width: 18rem;">
                <div class="card-body">
                    <lable>Order ID : </lable><p class="card-title">@Session["lastOrderId"]</p>
                    <lable>Order Date : </lable><p class="card-text">@Session["lastOrderDate"]</p>
                    <lable>Mode Of Payment : </lable><p class="card-title">@Session["lastOrderPaymentMode"]p>
                    <lable>Amount Paid : </lable><p class="card-text">@Session["lastOrderAmountPaid"]</p>
                    <button class="btn btn-outline-success">@Html.ActionLink("Send On Mail", "SendMail", "Buyer")</button>
                </div>
            </div>
            <br />
    </div>
</div>

@*@Html.ActionLink("Edit", "UpdateProducts", new { id = item.ProductId }) |
    @Html.ActionLink("Details", "DisplayAllProducts", new { id = item.ProductId }) |
    @Html.ActionLink("Delete", "DeleteProduct", new { id = item.ProductId })
            </td>*@

RepoPractice/Views/Buyer/Index.cshtml
@model IEnumerable<RepoPractice.Models.ProductModel>

<center>
    <h2> Products </h2>
</center>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>








<div class="row mt-5">

    <div class="col-lg-10 col-md-10 col-sm-10">
        @if (TempData["msg"] != null)
        {
            <div class="alert alert-success" role="alert" style="font-size:large">
                @TempData["msg"]
            </div>

        }
        @if (TempData["total"] == null)
        {

            <h3>
                Total Bill: 0 Rs
            </h3>
        }
        else
        {
            <h3> Total Bill: @TempData["total"] Rs</h3>

        }

    </div>


    <div class="col-lg-2 col-md-2 col-sm-2">
        <h3 style="font-family:'Arial Rounded MT';text-align:center"> <span class="btn btn-warning">@Html.ActionLink("Check Out", "Checkout", "Buyer")</span></h3>
    </div>




</div>

@*<div class="container">
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-lg-3">
                <div class="card" style="width: 18rem;">
                    <img style="min-height:200px;width:200px" src="@Url.Content(item.Image)">
                    <div class="card-body">
                        <p class="card-text"><h2>Brand</h2>@item.ProductName </p>
                        <p class="card-text"><h2>Price</h2>@item.Price</p>
                        <h4 style="color:#808080; font-family:'Arial Rounded MT';text-align:center"> <span class="btn btn-warning">@Html.ActionLink("Add To Cart", "Adtocart", new { id = @item.ProductId })</span></h4>
                    </div>
                </div>
            </div>}

    </div>


</div>*@

RepoPractice/Views/Buyer/PaymentMode.cshtml
@model RepoPractice.Models.OrderModel

<div style="margin-top:100px">
    <div class="container" style="margin-top:70px">
        <a href="javascript:void(0);" onclick="history.go(-1);">
            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
        </a>
    </div>
    @using (Html.BeginForm("OrderConfirmed", "Buyer", FormMethod.Post))
    {
        <input type="radio" id="COD" name="ModeOfPayment" value="COD" required>
        <label for="COD">COD</label><br>
        <input type="radio" id="Wallet" name="ModeOfPayment" value="Wallet">
        <label for="Wallet">Wallet</label><br>
        <button type="submit" class="btn btn-primary">Order</button>
    }
</div>

RepoPractice/Views/Buyer/Search.cshtml
@model IEnumerable<RepoPractice.Models.ProductModel>

<div id="carouselExampleIndicators" class="carousel slide mt-5 rounded-4 shadow" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner rounded-4">
        <div class="carousel-item active">
            <img src="~/Content/Image/carousel1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Content/Image/carousel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Content/Image/carousel3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="mt-lg-5">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="card shadow col-lg-3 m-4" style="width: 18rem;">
                <img src="@Url.Content(item.Image)" class="card-img-top" alt="...">
                <div class="card-body">
                    <lable>Product Name : </lable><h5 class="card-title">@Html.DisplayFor(modelItem => item.ProductName)</h5>
                    <lable>Price : </lable><p class="card-text">@Html.DisplayFor(modelItem => item.Price)</p>
                    <button class="btn btn-primary">@Html.ActionLink("Add To Cart", "AddToCart", new { id = item.ProductId }, new { @style = "text-decoration : none;color : white" })</button>
                </div>
            </div>
            <br />
        }
    </div>
</div>

@*@Html.ActionLink("Edit", "UpdateProducts", new { id = item.ProductId }) |
    @Html.ActionLink("Details", "DisplayAllProducts", new { id = item.ProductId }) |
    @Html.ActionLink("Delete", "DeleteProduct", new { id = item.ProductId })
            </td>*@

RepoPractice/Views/Buyer/UpdateProfile.cshtml
@model RepoPractice.Models.UserModel

@{
    ViewBag.Title = "UpdateProfile";
}

<h2>UpdateProfile</h2>

@using (Html.BeginForm())
{
    <div class="container" style="margin-top:70px">
        <a href="javascript:void(0);" onclick="history.go(-1);">
            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
        </a>
    </div>
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RepoPractice/Views/Buyer/ViewCart.cshtml
@{
    ViewBag.Title = "checkout";
}



<h2>ViewCart</h2>

<div class="container" style="margin-top:70px">
    <a href="javascript:void(0);" onclick="history.go(-1);">
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
        </svg>
    </a>
    </div>

    <table class="table table-responsive">

        <thead>
            <tr>
                <th>ID</th>
                <th>NAME</th>
                <th>PRICE</th>
                <th>QUANTITY</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {


                <tr>
                    <td>@item.ProductModel_ProductId </td>
                    <td>@item.productname</td>
                    <td>@item.price</td>
                    <td>@item.Quantity</td>
                    <td>@item.TotalAmount</td>
                    <td><a class="btn btn-danger btn-sm" href="@Url.Action("Remove", new { id = @item.CartId })">&#10060;</a></td>
                </tr>

            }


        </tbody>

         @*<tfoot>
            <tr>
                <td colspan="4"></td>
                <td>@TempData["total"]</td>

            </tr>
        </tfoot>*@

    </table>
    <h2>Grand Total : @ViewBag.GrandTotal</h2>

    <button class="btn btn-outline-success">@Html.ActionLink("Buy Now", "Checkout", "Buyer")</button>
    <button class="btn btn-outline-success">@Html.ActionLink("Add More Products", "BuyerDisplayAllProduct", "Buyer")</button>